#!/bin/sh
SPIRAL="`dirname $0`"
INSTALL_PFX="$SPIRAL/gap"
GAP_DIR=$SPIRAL/gap
GAP_MEM=2048m

export SPIRAL_CONFIG_TMP_DIR="/tmp/spiraltmp"
export SPIRAL_CONFIG_SPIRAL_DIR="$SPIRAL"
export SPIRAL_CONFIG_EXEC_DIR="/usr/local/bin"
export SPIRAL_CONFIG_PATH_SEP="/"

# add path to profiler
export PATH="$PATH:$SPIRAL/profiler/bin"

#== start SPIRAL
exec "$INSTALL_PFX/bin/gap" -m $GAP_MEM -x 1000 -l "$GAP_DIR/lib/" -h "$GAP_DIR/doc/"  $SPIRAL/_spiral.g

# /gap/lib is being added using -l "$GAP_DIR/lib/" but it can also be added using
# export SPIRAL_GAP_LIB_DIR=*input_path_to_gap/lib*
