/*
 *  Copyright (c) 2018-2021, Carnegie Mellon University
 *  See LICENSE for details
 */
 
/* sys_conf/conf.h.  Generated by configure.  */

#ifndef CONF_H_INCLUDED
#define CONF_H_INCLUDED

#define HAVE_GETTIMEOFDAY 1
#define HAVE_GETUID 1
#define HAVE_ISATTY 1
#define HAVE_UNISTD_H 1
#define HAVE_MKSTEMP 1

#define DEFAULT_CONFIG_FILE "/cygdrive/c/Documents and Settings/marekt/My Documents/spiral/spiral.conf"

#ifdef WIN32
#define QUOTIFY_SHELL_COMMAND 1
#define QUOTIFY_CHAR '\"'
#else
/* #undef QUOTIFY_SHELL_COMMAND */
#define QUOTIFY_CHAR '\''
#endif

#endif /* CONF_H_INCLUDED */

